// function splitOrder (postMap) {
//     try {
//         nlapiLogExecution('DEBUG', 'postMap data', postMap);
//     } catch (e) {
//         nlapiLogExecution('DEBUG', 'Exception', '');
//     }
// }
function splitOrder (data) {
    var response = [{
        "data": {},
        "errors": []
    }];
    try {
        var postMapData = data.postMapData[0];
        var items = postMapData.nlobjSublistIds.item.lines;
        var groupedItemsMap = {};
        var isUpdate = false;
        for (var i=0; i<items.length; i++) {
            var mappedItem = items[i];
            if (mappedItem['ns_order_id']) {
                isUpdate = true;
                break;
            }
        }        
        for (var i=0; i<items.length; i++) {
            var mappedItem = items[i];
            if (mappedItem['exclude_from_ns'] || mappedItem['rate'] < 0 ) {
                continue;
            }
            var itemKey = mappedItem.ns_batch_id;
            if (!itemKey) {
                itemKey = mappedItem["rev_rec_start_date"] + "|" + mappedItem["recurring_billing_frequency"];
            }
            if (!groupedItemsMap.hasOwnProperty(itemKey)) {
                groupedItemsMap[itemKey] = [];
            }
            groupedItemsMap[itemKey].push(mappedItem);
        }
        
        var ordersToCreate = [];
        for (var key in groupedItemsMap) {
            if (groupedItemsMap.hasOwnProperty(key)) {
                var orderObj = {};
                orderObj.nlobjRecordType = postMapData.nlobjRecordType;
                orderObj.nlobjFieldIds = postMapData.nlobjFieldIds;
                orderObj.nlobjSublistIds = {
                    "item": {
                        "lines": groupedItemsMap[key]
                    }
                }
                ordersToCreate.push(orderObj);
            }
        }

        $$.logExecution("DEBUG", "orders to create", JSON.stringify(ordersToCreate));
        
        if (ordersToCreate && ordersToCreate.length > 0) {
            response[0].data = ordersToCreate[0];
        }

        try {
            for (var i=1;i<ordersToCreate.length;i++) {
                $$.logExecution("DBUG", "Saving record: " + i, "");
                var record = new $R(ordersToCreate[i]);
                var recordId = record.save();
                $$.logExecution("DEBUG", "Sales order created: ", recordId);
            }
        } catch (e) {
            $$.logExecution("DEBUG", "unable to create order", e.message);
            response[0].data = {};
            response[0].errors = [{
                "message": "failed creating order: " + e.message
            }]
        }
    } catch (e) {
        $$.logExecution("DEBUG", "failed splitting order", e.message);
    }
    return response;
}

// var data = {
    
// 	"postMapData": [
// 		{
// 			"nlobjRecordType": "salesorder",
// 			"nlobjFieldIds": {
// 				"entity": "0012i000008GtEHAA0",
// 				"enddate": "2019-10-17"
// 			},
// 			"nlobjSublistIds": {},
// 			"documentIndex": 0,
// 			"exportedDoc": {
// 				"attributes": {
// 					"url": "/services/data/v35.0/sobjects/Opportunity/0062i000002CuDDAA0",
// 					"type": "Opportunity"
// 				},
// 				"Total_Opportunity_Product_Quantity__c": 3,
// 				"Quota_MRR__c": 294,
// 				"Net_MRR_Products__c": 294,
// 				"Migration_Quantity__c": 0,
// 				"Idle_Down_Quantity__c": 0,
// 				"Idle_Down_Only__c": false,
// 				"Override_Turn_Off_WWP_Rate_Change__c": false,
// 				"adroll__RollWorks_Influenced__c": false,
// 				"adroll__RollWorks_Influenced_Opportunity__c": false,
// 				"Net_MRR_Not_Equal__c": false,
// 				"Non_Sufficient_Funds_Fee__c": 20,
// 				"Chargeback_Fee__c": 15,
// 				"eCheck_Fee__c": 0.75,
// 				"Contract_Created__c": false,
// 				"WorkWave_Payments_Products__c": 0,
// 				"WWP_Contract_Transaction_Fee__c": "$00.30 Transaction Fee",
// 				"WWP_Contract_Rate__c": "0%",
// 				"Inventory_Hold_Stock__c": false,
// 				"Org_ID__c": "00D2i0000000dMi",
// 				"X18_Digit_Account_ID__c": "0012i000008GtEHAA0",
// 				"Primary_Software__c": "No Primary Product",
// 				"Sales_Transaction_Fee__c": 0.3,
// 				"WWP_Rate_Change_Requested_Completed__c": false,
// 				"Agreement_Length__c": 34,
// 				"Primary_Contact_ID__c": "0032i000006jVoVAAU",
// 				"Team1__c": "AE WorkWave Service",
// 				"Total_Bookings__c": false,
// 				"Quota_Bookings__c": false,
// 				"Commission_Payout__c": false,
// 				"Primary_Products_All__c": "WorkWave Service, ",
// 				"Billboard_Mini__c": "_IM1_/servlet/servlet.FileDownload?file=01530000003TJj3_IM2_WorkWave Service_IM3__20_IM4_-30_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004ZJM3_IM2_Approved_IM3__30_IM4_30_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004hBgH_IM2_Closed Won_IM3__30_IM4_30_IM5_ ",
// 				"Has_Custom_Agreement_Notes__c": false,
// 				"Owner_ID__c": "0053A00000CtQdH",
// 				"Net_MRR_Text__c": 294,
// 				"Team__c": "AE WorkWave Service",
// 				"Owner_Name__c": "Phil Heckendorf",
// 				"Create_Agreement__c": "_HL_ENCODED_/apex/APXTConga4__Conga_Composer?serverUrl=https://cs37.salesforce.com/services/Soap/u/37.0/00D2i0000000dMi&id=0062i000002CuDD&ESVisible=1&ESSignatureOrder=1&ESRequireSelfSign=1&ESSignatureType=2&ESAccountId=0012i000008GtEH&ESPreview=1&ESAgreementName=Agreement+for+Company A&ESMessage=Please+sign+and+return.+If+you+have+any+questions+please+contact+me+at+800.762.0301+Thank+you,+WorkWave_HL__IM1_/servlet/servlet.FileDownload?file=0153A000004HanH_IM2_Create Agreement_IM3__HL__blank_HL_",
// 				"Won__c": 1,
// 				"SAO__c": 1,
// 				"Marketing_Services_Products__c": 0,
// 				"Primary_Product__c": "WorkWave Service",
// 				"Finance_Marked_as_Error__c": false,
// 				"Mins_in_Initial_Queue__c": 10364,
// 				"Billboard__c": "_IM1_/servlet/servlet.FileDownload?file=01530000003TJj3_IM2_WorkWave Service_IM3__50_IM4_-75_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004ZJM3_IM2_Approved_IM3__50_IM4_50_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004hBgH_IM2_Closed Won_IM3__50_IM4_50_IM5_",
// 				"Opp_Review_Total_Time_Mins__c": 2,
// 				"Primary_Contact__c": "0032i000006jVoVAAU",
// 				"Software_Currently_Used__c": "* Prospect won't give Competitive info",
// 				"Future_Start_Date_Cancelled__c": false,
// 				"Reviewed_with_Team__c": false,
// 				"Is_Demo_Account__c": false,
// 				"Commission_Approved__c": false,
// 				"SAO_Date__c": "2019-10-17",
// 				"Account_Company_Size__c": "SB",
// 				"Owner_Fullname__c": " Charan",
// 				"Opportunity_Error_Resolved__c": false,
// 				"Opportunity_Error__c": false,
// 				"Proof_of_Concept__c": false,
// 				"Sales_Target_Monthly__c": 0,
// 				"Reconciliation_Opp__c": false,
// 				"Cost_Per_Period_Total__c": 489,
// 				"Account_GPS_Price_Increase__c": false,
// 				"PestPac_Enterprise_Plus_Bundle__c": 0,
// 				"Primary_Campaign_Type_Reporting__c": "Directory",
// 				"Idle_Down_Not_Required__c": false,
// 				"Primary_Campaign_Type__c": "Directory",
// 				"Net_MRR__c": 294,
// 				"Account_Enterprise_Potential__c": false,
// 				"Closed_Timestamp__c": "2019-10-17T14:08:47.000Z",
// 				"ES_Timestamp__c": "2019-10-17T14:08:47.000Z",
// 				"WWP_Agreement_Name__c": "WWPmts Contract/Consent Company A-",
// 				"Primary_Campaign_ID__c": "7013A000002IRut",
// 				"Forms_Payment_Recieved__c": false,
// 				"Forecast_Probability__c": 100,
// 				"Website_Agency_Products__c": 0,
// 				"First_Cross_Sell__c": false,
// 				"Standard_or_Enterprise__c": "Standard",
// 				"Software_MRR__c": 294,
// 				"Marketing_MRR__c": 0,
// 				"Enterprise_Opportunity__c": false,
// 				"Opportunity_Stage_Summary__c": "Won",
// 				"Pipeline_Close_Date__c": "2019-10-17",
// 				"Type_Primary_Campaign_Source__c": "Directory",
// 				"One_Time_Backup_Products__c": 0,
// 				"Total_Recurring_Contract_Value__c": 3528,
// 				"Opportunity_Asset_Flag__c": true,
// 				"Owner_Role__c": "WWS AE - Sales, Field Services",
// 				"ContactUs_Reviews_From_Website_Package__c": 0,
// 				"Ignore_OE__c": false,
// 				"Is_Null_Test__c": true,
// 				"WorkWave_Service_Products__c": 3,
// 				"WorkWave_Route_Manager_Products__c": 0,
// 				"WorkWave_Marketing_Products__c": 0,
// 				"WorkWave_GPS_Products__c": 0,
// 				"Viamente_Products__c": 0,
// 				"ServiceCEO_Products__c": 0,
// 				"QxPress_Products__c": 0,
// 				"PestPac_Products__c": 0,
// 				"PestPac_MA_Products__c": 0,
// 				"PestPac_LM_Products__c": 0,
// 				"GPS_Heroes_Products__c": 0,
// 				"ContactUs_Reviews_Products__c": 0,
// 				"ContactUs_Products__c": 0,
// 				"Override_Auto_Create_Admin_Case__c": false,
// 				"Verified_Active_Asset_Updates__c": 0,
// 				"Products_Under_Minimum_Discount__c": 0,
// 				"Highest_Discount_Percent__c": 0,
// 				"Automatically_Manage_Assets__c": true,
// 				"IsClone__c": false,
// 				"CFCR_Velocity_Won__c": 0,
// 				"OppCountWon__c": 1,
// 				"Count__c": 1,
// 				"Account_Type_Formula__c": "Customer",
// 				"CFCR_Exclude_From_Campaign_Influence__c": false,
// 				"Create_Date_Time__c": "2019-10-17T14:01:06.000Z",
// 				"Exclude_From_Timing_Rules__c": false,
// 				"Within_Business_Hours_VP__c": "Yes",
// 				"Within_Business_Hours_Extension__c": "Yes",
// 				"Within_Business_Hours_Created__c": "Yes",
// 				"Send_Second_Notification_VP__c": false,
// 				"Send_Second_Notification_CL__c": false,
// 				"Send_First_Notification_VP__c": false,
// 				"Send_First_Notification_CL__c": false,
// 				"Send_First_Notification_CL_3_Days__c": false,
// 				"Send_Final_Notification_VP__c": false,
// 				"Send_Final_Notification_Open_Opp__c": false,
// 				"Request_Time_Extension__c": false,
// 				"Opportunity_Auto_Closed__c": false,
// 				"WWGPS_Product_Count__c": 0,
// 				"WWRM_Product_Count__c": 0,
// 				"PestPac_Product_Count__c": 0,
// 				"GPSH_Verizon_Activated__c": false,
// 				"GPSH_Biz_Updated__c": false,
// 				"Opp_Review_Submitted_TS__c": "2019-10-17T14:06:12.000Z",
// 				"Opp_Review_Completed_TS__c": "2019-10-17T14:07:47.000Z",
// 				"Sort__c": 2,
// 				"Opp_Review_Status__c": "Approved",
// 				"Opp_Review_Approved__c": 1,
// 				"Chatter_for_Approvel_Process__c": "This opportunity has been APPROVED to send out!",
// 				"Stock_Order_Confirmed__c": false,
// 				"Days_To_Close__c": 0,
// 				"netsuite_conn__Push_as_NetSuite_Project__c": false,
// 				"netsuite_conn__Push_as_NetSuite_Opportunity__c": false,
// 				"FuseBill_Migration__c": false,
// 				"LMP_Product_Count__c": 0,
// 				"PSUB_Product_Count__c": 0,
// 				"Upfront_Total_Monthly_Deals_2MO__c": 783,
// 				"Closed_Quarter__c": "Q4",
// 				"Upfront_Total_Annual_Deals__c": 3723,
// 				"Last_Completed_Activity_Date__c": "2019-07-09",
// 				"Upfront_Total__c": 489,
// 				"ES_Date__c": "2019-10-17",
// 				"Annual_Increase_Percentage__c": 5,
// 				"Manager__c": "0053A00000CB0utQAD",
// 				"Lock_Opportunity__c": false,
// 				"Created_Timestamp__c": "2019-10-17T14:01:06.000Z",
// 				"Pushed_Via_Button__c": false,
// 				"Total_Invoice_Amount__c": 489,
// 				"netsuite_conn__Sync_In_Progress__c": false,
// 				"netsuite_conn__Push_To_NetSuite__c": true,
// 				"netsuite_conn__Originated_From_NetSuite__c": false,
// 				"netsuite_conn__Celigo_Update__c": false,
// 				"Inferred_Lead_Source__c": "Directory",
// 				"Closed_Year__c": "2019",
// 				"Closed_Week__c": "Week 3",
// 				"Closed_Month__c": "10 - October",
// 				"Created_Year__c": "2019",
// 				"Created_Week__c": "Week 3",
// 				"Setup_Fee__c": false,
// 				"Created_Month__c": "10 - October",
// 				"Prepay__c": false,
// 				"Trial_Deactivated__c": false,
// 				"Trial_Activated__c": false,
// 				"Snap_Timeframe__c": "End",
// 				"Opp_Owner_Account_Owner__c": true,
// 				"Won_MRR__c": 294,
// 				"CSM_Referral__c": false,
// 				"Admin_Trigger__c": false,
// 				"Lead_Converted__c": true,
// 				"Lead_Source_Contact_Method__c": "Form",
// 				"One_Time_Revenue_Total__c": 195,
// 				"Volo_Candidate__c": false,
// 				"Opp_Num__c": "O-204037",
// 				"MRR_Total__c": 294,
// 				"Trial__c": false,
// 				"cirrusadv__Created_by_Cirrus_Insight__c": false,
// 				"OppCount__c": 1,
// 				"Num_of_User_Licenses__c": "1-9",
// 				"X30_day_Opt_out__c": false,
// 				"Demo_Held__c": false,
// 				"ServMan_Product_Count__c": 0,
// 				"Fleet_Simulations__c": false,
// 				"Evergreen__c": false,
// 				"Snapshot_Name__c": "SN-2019-10-24-O-204037",
// 				"Funnel__c": "a1T3A000005jRM7UAM",
// 				"Multi_Year_Term__c": false,
// 				"Opp_Type_from_Lead__c": "Field Services",
// 				"Verified__c": false,
// 				"Initial_Product_Requested__c": "WorkWave Service",
// 				"X18_Digit_Opportunity_ID__c": "0062i000002CuDDAA0",
// 				"mkto_si__MarketoAnalyzer__c": "_HL_ENCODED_/apex/mkto_si__MarketoRedirect?actionName=salesInsightAnalytics&reportType=AccountAnalyzer&objType=Opportunity&objId=0062i000002CuDD_HL__IM1_https://app.marketo.com/images/icons16/marketo16.png_IM2_Marketo Opportunity Analysis_IM3__HL__blank_HL_",
// 				"Out_of_Call_List__c": false,
// 				"ARR_Total__c": 3528,
// 				"Opportunity_Number__c": "00214821",
// 				"HasOverdueTask": false,
// 				"HasOpenActivity": false,
// 				"LastActivityDate": "2019-07-09",
// 				"SystemModstamp": "2019-10-24T18:49:48.000Z",
// 				"LastModifiedById": "0052i000000lP7qAAE",
// 				"LastModifiedDate": "2019-10-24T18:49:48.000Z",
// 				"CreatedById": "0053A00000CtQdHQAV",
// 				"CreatedDate": "2019-10-17T14:01:06.000Z",
// 				"OwnerId": "0053A00000CtQdHQAV",
// 				"Pricebook2Id": "01s3A000000NfqZQAS",
// 				"IsSplit": true,
// 				"HasOpportunityLineItem": true,
// 				"CampaignId": "7013A000002IRutQAG",
// 				"ForecastCategoryName": "Closed",
// 				"ForecastCategory": "Closed",
// 				"IsWon": true,
// 				"IsClosed": true,
// 				"LeadSource": "Directory",
// 				"Type": "New",
// 				"CloseDate": "2019-10-17",
// 				"TotalOpportunityQuantity": 3,
// 				"ExpectedRevenue": 489,
// 				"Probability": 100,
// 				"Amount": 489,
// 				"StageName": "Closed/Won",
// 				"Name": "Company A [O-204037] -Field Services-New",
// 				"IsPrivate": false,
// 				"RecordTypeId": "012300000019SCfAAM",
// 				"AccountId": "0012i000008GtEHAA0",
// 				"IsDeleted": false,
// 				"Id": "0062i000002CuDDAA0"
// 			}
// 		}
// 	],
// 	"preMapData": [
// 		{
// 			"attributes": {
// 				"url": "/services/data/v35.0/sobjects/Opportunity/0062i000002CuDDAA0",
// 				"type": "Opportunity"
// 			},
// 			"Total_Opportunity_Product_Quantity__c": 3,
// 			"Quota_MRR__c": 294,
// 			"Net_MRR_Products__c": 294,
// 			"Migration_Quantity__c": 0,
// 			"Idle_Down_Quantity__c": 0,
// 			"Idle_Down_Only__c": false,
// 			"Override_Turn_Off_WWP_Rate_Change__c": false,
// 			"adroll__RollWorks_Influenced__c": false,
// 			"adroll__RollWorks_Influenced_Opportunity__c": false,
// 			"Net_MRR_Not_Equal__c": false,
// 			"Non_Sufficient_Funds_Fee__c": 20,
// 			"Chargeback_Fee__c": 15,
// 			"eCheck_Fee__c": 0.75,
// 			"Contract_Created__c": false,
// 			"WorkWave_Payments_Products__c": 0,
// 			"WWP_Contract_Transaction_Fee__c": "$00.30 Transaction Fee",
// 			"WWP_Contract_Rate__c": "0%",
// 			"Inventory_Hold_Stock__c": false,
// 			"Org_ID__c": "00D2i0000000dMi",
// 			"X18_Digit_Account_ID__c": "0012i000008GtEHAA0",
// 			"Primary_Software__c": "No Primary Product",
// 			"Sales_Transaction_Fee__c": 0.3,
// 			"WWP_Rate_Change_Requested_Completed__c": false,
// 			"Agreement_Length__c": 34,
// 			"Primary_Contact_ID__c": "0032i000006jVoVAAU",
// 			"Team1__c": "AE WorkWave Service",
// 			"Total_Bookings__c": false,
// 			"Quota_Bookings__c": false,
// 			"Commission_Payout__c": false,
// 			"Primary_Products_All__c": "WorkWave Service, ",
// 			"Billboard_Mini__c": "_IM1_/servlet/servlet.FileDownload?file=01530000003TJj3_IM2_WorkWave Service_IM3__20_IM4_-30_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004ZJM3_IM2_Approved_IM3__30_IM4_30_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004hBgH_IM2_Closed Won_IM3__30_IM4_30_IM5_ ",
// 			"Has_Custom_Agreement_Notes__c": false,
// 			"Owner_ID__c": "0053A00000CtQdH",
// 			"Net_MRR_Text__c": 294,
// 			"Team__c": "AE WorkWave Service",
// 			"Owner_Name__c": "Phil Heckendorf",
// 			"Create_Agreement__c": "_HL_ENCODED_/apex/APXTConga4__Conga_Composer?serverUrl=https://cs37.salesforce.com/services/Soap/u/37.0/00D2i0000000dMi&id=0062i000002CuDD&ESVisible=1&ESSignatureOrder=1&ESRequireSelfSign=1&ESSignatureType=2&ESAccountId=0012i000008GtEH&ESPreview=1&ESAgreementName=Agreement+for+Company A&ESMessage=Please+sign+and+return.+If+you+have+any+questions+please+contact+me+at+800.762.0301+Thank+you,+WorkWave_HL__IM1_/servlet/servlet.FileDownload?file=0153A000004HanH_IM2_Create Agreement_IM3__HL__blank_HL_",
// 			"Won__c": 1,
// 			"SAO__c": 1,
// 			"Marketing_Services_Products__c": 0,
// 			"Primary_Product__c": "WorkWave Service",
// 			"Finance_Marked_as_Error__c": false,
// 			"Mins_in_Initial_Queue__c": 10364,
// 			"Billboard__c": "_IM1_/servlet/servlet.FileDownload?file=01530000003TJj3_IM2_WorkWave Service_IM3__50_IM4_-75_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004ZJM3_IM2_Approved_IM3__50_IM4_50_IM5_ _IM1_/servlet/servlet.FileDownload?file=0153A000004hBgH_IM2_Closed Won_IM3__50_IM4_50_IM5_",
// 			"Opp_Review_Total_Time_Mins__c": 2,
// 			"Primary_Contact__c": "0032i000006jVoVAAU",
// 			"Software_Currently_Used__c": "* Prospect won't give Competitive info",
// 			"Future_Start_Date_Cancelled__c": false,
// 			"Reviewed_with_Team__c": false,
// 			"Is_Demo_Account__c": false,
// 			"Commission_Approved__c": false,
// 			"SAO_Date__c": "2019-10-17",
// 			"Account_Company_Size__c": "SB",
// 			"Owner_Fullname__c": " Charan",
// 			"Opportunity_Error_Resolved__c": false,
// 			"Opportunity_Error__c": false,
// 			"Proof_of_Concept__c": false,
// 			"Sales_Target_Monthly__c": 0,
// 			"Reconciliation_Opp__c": false,
// 			"Cost_Per_Period_Total__c": 489,
// 			"Account_GPS_Price_Increase__c": false,
// 			"PestPac_Enterprise_Plus_Bundle__c": 0,
// 			"Primary_Campaign_Type_Reporting__c": "Directory",
// 			"Idle_Down_Not_Required__c": false,
// 			"Primary_Campaign_Type__c": "Directory",
// 			"Net_MRR__c": 294,
// 			"Account_Enterprise_Potential__c": false,
// 			"Closed_Timestamp__c": "2019-10-17T14:08:47.000Z",
// 			"ES_Timestamp__c": "2019-10-17T14:08:47.000Z",
// 			"WWP_Agreement_Name__c": "WWPmts Contract/Consent Company A-",
// 			"Primary_Campaign_ID__c": "7013A000002IRut",
// 			"Forms_Payment_Recieved__c": false,
// 			"Forecast_Probability__c": 100,
// 			"Website_Agency_Products__c": 0,
// 			"First_Cross_Sell__c": false,
// 			"Standard_or_Enterprise__c": "Standard",
// 			"Software_MRR__c": 294,
// 			"Marketing_MRR__c": 0,
// 			"Enterprise_Opportunity__c": false,
// 			"Opportunity_Stage_Summary__c": "Won",
// 			"Pipeline_Close_Date__c": "2019-10-17",
// 			"Type_Primary_Campaign_Source__c": "Directory",
// 			"One_Time_Backup_Products__c": 0,
// 			"Total_Recurring_Contract_Value__c": 3528,
// 			"Opportunity_Asset_Flag__c": true,
// 			"Owner_Role__c": "WWS AE - Sales, Field Services",
// 			"ContactUs_Reviews_From_Website_Package__c": 0,
// 			"Ignore_OE__c": false,
// 			"Is_Null_Test__c": true,
// 			"WorkWave_Service_Products__c": 3,
// 			"WorkWave_Route_Manager_Products__c": 0,
// 			"WorkWave_Marketing_Products__c": 0,
// 			"WorkWave_GPS_Products__c": 0,
// 			"Viamente_Products__c": 0,
// 			"ServiceCEO_Products__c": 0,
// 			"QxPress_Products__c": 0,
// 			"PestPac_Products__c": 0,
// 			"PestPac_MA_Products__c": 0,
// 			"PestPac_LM_Products__c": 0,
// 			"GPS_Heroes_Products__c": 0,
// 			"ContactUs_Reviews_Products__c": 0,
// 			"ContactUs_Products__c": 0,
// 			"Override_Auto_Create_Admin_Case__c": false,
// 			"Verified_Active_Asset_Updates__c": 0,
// 			"Products_Under_Minimum_Discount__c": 0,
// 			"Highest_Discount_Percent__c": 0,
// 			"Automatically_Manage_Assets__c": true,
// 			"IsClone__c": false,
// 			"CFCR_Velocity_Won__c": 0,
// 			"OppCountWon__c": 1,
// 			"Count__c": 1,
// 			"Account_Type_Formula__c": "Customer",
// 			"CFCR_Exclude_From_Campaign_Influence__c": false,
// 			"Create_Date_Time__c": "2019-10-17T14:01:06.000Z",
// 			"Exclude_From_Timing_Rules__c": false,
// 			"Within_Business_Hours_VP__c": "Yes",
// 			"Within_Business_Hours_Extension__c": "Yes",
// 			"Within_Business_Hours_Created__c": "Yes",
// 			"Send_Second_Notification_VP__c": false,
// 			"Send_Second_Notification_CL__c": false,
// 			"Send_First_Notification_VP__c": false,
// 			"Send_First_Notification_CL__c": false,
// 			"Send_First_Notification_CL_3_Days__c": false,
// 			"Send_Final_Notification_VP__c": false,
// 			"Send_Final_Notification_Open_Opp__c": false,
// 			"Request_Time_Extension__c": false,
// 			"Opportunity_Auto_Closed__c": false,
// 			"WWGPS_Product_Count__c": 0,
// 			"WWRM_Product_Count__c": 0,
// 			"PestPac_Product_Count__c": 0,
// 			"GPSH_Verizon_Activated__c": false,
// 			"GPSH_Biz_Updated__c": false,
// 			"Opp_Review_Submitted_TS__c": "2019-10-17T14:06:12.000Z",
// 			"Opp_Review_Completed_TS__c": "2019-10-17T14:07:47.000Z",
// 			"Sort__c": 2,
// 			"Opp_Review_Status__c": "Approved",
// 			"Opp_Review_Approved__c": 1,
// 			"Chatter_for_Approvel_Process__c": "This opportunity has been APPROVED to send out!",
// 			"Stock_Order_Confirmed__c": false,
// 			"Days_To_Close__c": 0,
// 			"netsuite_conn__Push_as_NetSuite_Project__c": false,
// 			"netsuite_conn__Push_as_NetSuite_Opportunity__c": false,
// 			"FuseBill_Migration__c": false,
// 			"LMP_Product_Count__c": 0,
// 			"PSUB_Product_Count__c": 0,
// 			"Upfront_Total_Monthly_Deals_2MO__c": 783,
// 			"Closed_Quarter__c": "Q4",
// 			"Upfront_Total_Annual_Deals__c": 3723,
// 			"Last_Completed_Activity_Date__c": "2019-07-09",
// 			"Upfront_Total__c": 489,
// 			"ES_Date__c": "2019-10-17",
// 			"Annual_Increase_Percentage__c": 5,
// 			"Manager__c": "0053A00000CB0utQAD",
// 			"Lock_Opportunity__c": false,
// 			"Created_Timestamp__c": "2019-10-17T14:01:06.000Z",
// 			"Pushed_Via_Button__c": false,
// 			"Total_Invoice_Amount__c": 489,
// 			"netsuite_conn__Sync_In_Progress__c": false,
// 			"netsuite_conn__Push_To_NetSuite__c": true,
// 			"netsuite_conn__Originated_From_NetSuite__c": false,
// 			"netsuite_conn__Celigo_Update__c": false,
// 			"Inferred_Lead_Source__c": "Directory",
// 			"Closed_Year__c": "2019",
// 			"Closed_Week__c": "Week 3",
// 			"Closed_Month__c": "10 - October",
// 			"Created_Year__c": "2019",
// 			"Created_Week__c": "Week 3",
// 			"Setup_Fee__c": false,
// 			"Created_Month__c": "10 - October",
// 			"Prepay__c": false,
// 			"Trial_Deactivated__c": false,
// 			"Trial_Activated__c": false,
// 			"Snap_Timeframe__c": "End",
// 			"Opp_Owner_Account_Owner__c": true,
// 			"Won_MRR__c": 294,
// 			"CSM_Referral__c": false,
// 			"Admin_Trigger__c": false,
// 			"Lead_Converted__c": true,
// 			"Lead_Source_Contact_Method__c": "Form",
// 			"One_Time_Revenue_Total__c": 195,
// 			"Volo_Candidate__c": false,
// 			"Opp_Num__c": "O-204037",
// 			"MRR_Total__c": 294,
// 			"Trial__c": false,
// 			"cirrusadv__Created_by_Cirrus_Insight__c": false,
// 			"OppCount__c": 1,
// 			"Num_of_User_Licenses__c": "1-9",
// 			"X30_day_Opt_out__c": false,
// 			"Demo_Held__c": false,
// 			"ServMan_Product_Count__c": 0,
// 			"Fleet_Simulations__c": false,
// 			"Evergreen__c": false,
// 			"Snapshot_Name__c": "SN-2019-10-24-O-204037",
// 			"Funnel__c": "a1T3A000005jRM7UAM",
// 			"Multi_Year_Term__c": false,
// 			"Opp_Type_from_Lead__c": "Field Services",
// 			"Verified__c": false,
// 			"Initial_Product_Requested__c": "WorkWave Service",
// 			"X18_Digit_Opportunity_ID__c": "0062i000002CuDDAA0",
// 			"mkto_si__MarketoAnalyzer__c": "_HL_ENCODED_/apex/mkto_si__MarketoRedirect?actionName=salesInsightAnalytics&reportType=AccountAnalyzer&objType=Opportunity&objId=0062i000002CuDD_HL__IM1_https://app.marketo.com/images/icons16/marketo16.png_IM2_Marketo Opportunity Analysis_IM3__HL__blank_HL_",
// 			"Out_of_Call_List__c": false,
// 			"ARR_Total__c": 3528,
// 			"Opportunity_Number__c": "00214821",
// 			"HasOverdueTask": false,
// 			"HasOpenActivity": false,
// 			"LastActivityDate": "2019-07-09",
// 			"SystemModstamp": "2019-10-24T18:49:48.000Z",
// 			"LastModifiedById": "0052i000000lP7qAAE",
// 			"LastModifiedDate": "2019-10-24T18:49:48.000Z",
// 			"CreatedById": "0053A00000CtQdHQAV",
// 			"CreatedDate": "2019-10-17T14:01:06.000Z",
// 			"OwnerId": "0053A00000CtQdHQAV",
// 			"Pricebook2Id": "01s3A000000NfqZQAS",
// 			"IsSplit": true,
// 			"HasOpportunityLineItem": true,
// 			"CampaignId": "7013A000002IRutQAG",
// 			"ForecastCategoryName": "Closed",
// 			"ForecastCategory": "Closed",
// 			"IsWon": true,
// 			"IsClosed": true,
// 			"LeadSource": "Directory",
// 			"Type": "New",
// 			"CloseDate": "2019-10-17",
// 			"TotalOpportunityQuantity": 3,
// 			"ExpectedRevenue": 489,
// 			"Probability": 100,
// 			"Amount": 489,
// 			"StageName": "Closed/Won",
// 			"Name": "Company A [O-204037] -Field Services-New",
// 			"IsPrivate": false,
// 			"RecordTypeId": "012300000019SCfAAM",
// 			"AccountId": "0012i000008GtEHAA0",
// 			"IsDeleted": false,
// 			"Id": "0062i000002CuDDAA0"
// 		}
// 	],
// 	"settings": {},
// 	"_importId": "5dadc3f9ebb8470ca3cefa33",
// 	"configuration": {}
// }